export const weatherCardMapping = {
  snow: {
    iconName: "ac_unit",
    iconColor: "text-blue-400",
    bgColor: "bg-slate-800",
    textColor: "text-slate-100",
  },
  rain: {
    iconName: "rainy",
    iconColor: "text-blue-500",
    bgColor: "bg-slate-800",
    textColor: "text-slate-100",
  },
  fog: {
    iconName: "foggy",
    iconColor: "text-gray-400",
    bgColor: "bg-slate-900",
    textColor: "text-gray-200",
  },
  wind: {
    iconName: "air",
    iconColor: "text-emerald-400",
    bgColor: "bg-slate-800",
    textColor: "text-slate-100",
  },
  cloudy: {
    iconName: "cloud",
    iconColor: "text-gray-300",
    bgColor: "bg-slate-800",
    textColor: "text-gray-100",
  },
  "partly-cloudy-day": {
    iconName: "partly_cloudy_day",
    iconColor: "text-yellow-400",
    bgColor: "bg-slate-900",
    textColor: "text-gray-100",
  },
  "partly-cloudy-night": {
    iconName: "partly_cloudy_night",
    iconColor: "text-indigo-400",
    bgColor: "bg-slate-900",
    textColor: "text-gray-100",
  },
  "clear-day": {
    iconName: "sunny",
    iconColor: "text-amber-400",
    bgColor: "bg-slate-800",
    textColor: "text-white",
  },
  "clear-night": {
    iconName: "nights_stay",
    iconColor: "text-purple-400",
    bgColor: "bg-slate-900",
    textColor: "text-gray-100",
  },
  "snow-showers-day": {
    iconName: "weather_snowy",
    iconColor: "text-cyan-400",
    bgColor: "bg-slate-900",
    textColor: "text-gray-100",
  },
  "snow-showers-night": {
    iconName: "weather_snowy",
    iconColor: "text-indigo-400",
    bgColor: "bg-slate-900",
    textColor: "text-gray-100",
  },
  "thunder-rain": {
    iconName: "thunderstorm",
    iconColor: "text-purple-400",
    bgColor: "bg-slate-900",
    textColor: "text-gray-100",
  },
  "thunder-showers-day": {
    iconName: "storm",
    iconColor: "text-cyan-400",
    bgColor: "bg-slate-800",
    textColor: "text-gray-100",
  },
  "thunder-showers-night": {
    iconName: "storm",
    iconColor: "text-teal-400",
    bgColor: "bg-slate-900",
    textColor: "text-gray-100",
  },
  "showers-day": {
    iconName: "water_drop",
    iconColor: "text-teal-400",
    bgColor: "bg-slate-800",
    textColor: "text-gray-100",
  },
  "showers-night": {
    iconName: "water_drop",
    iconColor: "text-blue-400",
    bgColor: "bg-slate-900",
    textColor: "text-gray-100",
  },
};
